import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  // 光绘系列
  lightPaintingSeries: [
    {type: 'autogenerated', dirName: 'light-painting-series'},
  ],
  // 控制器系列
  controllerSeries: [
    {type: 'autogenerated', dirName: 'light-painting-controller'},
  ],
  // 动态光绘系列
  dynamicLightPaintingSeries: [
    {type: 'autogenerated', dirName: 'dynamic-light-painting-host'},
  ],
};

export default sidebars;
